steps:
  entrypoint: 'bash'
  args: [
    './helpers/init_git_repo.sh'
  ]
  env: [
    'COMMIT_SHA=${COMMIT_SHA}',
    'BASE_REPO_URL=https://github.com/devisahay/CalculatorLibrary.git',
    'BASE_BRANCH=${_BASE_BRANCH}',
    'PR_NUMBER=${_PR_NUMBER}'
  ]
  id: 'init-git-repo'